version: "3"

services:
  nginx:
    build: .docker/nginx
    ports:
      - "8080:80"
    networks:
      - fc
    depends_on:
      - node

  db:
    build: .docker/mysql
    image: mysql
    restart: always
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - fc

  node:
    build: .docker/node
    entrypoint: .docker/node/entrypoint.sh
    image: node:16
    restart: always
    environment:
      - PORT=3000
    networks:
      - fc
    volumes:
      - .:/app/
    depends_on:
      - db

networks:
  fc:
    driver: bridge
